### ISSUE TITLE
Trzecie zadanie ma złe rozwiązanie w autograde

### ISSUE THREAD

**Issue by mtizim** [korona-science/homework-mtizim#1]
Odnośnie funkcji no_new_cases_count

Mój kod który przechodzi wszystkie testy liczy **"Province/State"** w których liczba infekcji była **różna** od liczby infekcji w poprzednim dniu, zamiast tego co jest wyspecyfikowane w zadaniu.

Poprawnym rozwiązaniem zadania byłoby na przykład (po prawej porównanie do "poprawnego" rozwiązania)
```
from datetime import date,timedelta
given = date(year,month,day)
prev = given - timedelta(days=1)
fgiven = f"{given.month}/{given.day}/{str(given.year)[2:]}"
fprev =  f"{prev.month}/{prev.day}/{str(prev.year)[2:]}"
df = confirmed_cases[["Country/Region",fprev,fgiven]]\
    .groupby("Country/Region").sum()\                      <--- linijka różnicy
    .reset_index()
return df[df[fgiven]==df[fprev]].count()[0]                <--- "==" zamiast "!="
```

**Comment by RouNNdeL** [comment]
Zgadza sie, przepraszamy
